### ISSUE TITLE
Creation failed "ZIP does not support timestamps before 1980"

### ISSUE THREAD

**Issue by Rava77** [Nachtalb/PixivDownloader#2]
Creation failed. My system x86-64 Slackware with Python 3.10.
The last printed errors are these:

  File "/usr/lib64/python3.10/zipfile.py", line 1728, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/usr/lib64/python3.10/zipfile.py", line 518, in from_file
    zinfo = cls(arcname, date_time)
  File "/usr/lib64/python3.10/zipfile.py", line 362, in __init__
    raise ValueError('ZIP does not support timestamps before 1980')
ValueError: ZIP does not support timestamps before 1980

Indeed there are files and folders with the date of 1970-01-01

**Comment by Rava77** [comment]
I managed to overcome the ZIP timestamp issue via
cd pixivdownloader-0.1.1
find .  -exec touch {} \;

but it still fails:

pixivdownloader 0.1.1 is already the active version in easy-install.pth
Installing pixiv script to /usr/bin

Installed /usr/lib64/python3.10/site-packages/pixivdownloader-0.1.1-py3.10.egg
Processing dependencies for pixivdownloader==0.1.1
Searching for opencv-python
Reading https://pypi.org/simple/opencv-python/
Downloading https://files.pythonhosted.org/packages/b6/82/0519fdbbcaddc0fa8c2568327a8311477315a91b4513738ee1d35f0ce715/opencv-python-4.5.4.58.tar.gz#sha256=48288428f407bacba5f73d460feb4a1ecafe87db3d7cfc0730a49fb32f589bbf
Best match: opencv-python 4.5.4.58
Processing opencv-python-4.5.4.58.tar.gz
Writing /tmp/easy_install-xj3epnmw/opencv-python-4.5.4.58/setup.cfg
Running opencv-python-4.5.4.58/setup.py -q bdist_egg --dist-dir /tmp/easy_install-xj3epnmw/opencv-python-4.5.4.58/egg-dist-tmp-7w6dx726
Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/usr/lib64/python3.10/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib64/python3.10/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib64/python3.10/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-xj3epnmw/opencv-python-4.5.4.58/setup.py", line 10, in <module>
    long_description='%s\n\n%s' % (Path('README.rst').read_text(),
ModuleNotFoundError: No module named 'skbuild'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/sdb3/tmp/tmp/EINSORTIEREN/pixivdownloader-0.1.1/setup.py", line 7, in <module>
    setup(name='pixivdownloader',
  File "/usr/lib64/python3.10/site-packages/setuptools/__init__.py", line 159, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.10/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/usr/lib64/python3.10/site-packages/setuptools/command/install.py", line 124, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/usr/lib64/python3.10/site-packages/setuptools/command/easy_install.py", line 414, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib64/python3.10/site-packages/setuptools/command/easy_install.py", line 656, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib64/python3.10/site-packages/setuptools/command/easy_install.py", line 703, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib64/python3.10/site-packages/setuptools/command/easy_install.py", line 750, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/usr/lib64/python3.10/site-packages/pkg_resources/__init__.py", line 766, in resolve
    dist = best[req.key] = env.best_match(
  File "/usr/lib64/python3.10/site-packages/pkg_resources/__init__.py", line 1051, in best_match
    return self.obtain(req, installer)
  File "/usr/lib64/python3.10/site-packages/pkg_resources/__init__.py", line 1063, in obtain
    return installer(requirement)
  File "/usr/lib64/python3.10/site-packages/setuptools/command/easy_install.py", line 675, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib64/python3.10/site-packages/setuptools/command/easy_install.py", line 701, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib64/python3.10/site-packages/setuptools/command/easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib64/python3.10/site-packages/setuptools/command/easy_install.py", line 1168, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib64/python3.10/site-packages/setuptools/command/easy_install.py", line 1152, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib64/python3.10/site-packages/setuptools/sandbox.py", line 249, in run_setup
    with setup_context(setup_dir):
  File "/usr/lib64/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib64/python3.10/site-packages/setuptools/sandbox.py", line 190, in setup_context
    with save_modules():
  File "/usr/lib64/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib64/python3.10/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/usr/lib64/python3.10/site-packages/setuptools/sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "/usr/lib64/python3.10/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/usr/lib64/python3.10/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib64/python3.10/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib64/python3.10/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-xj3epnmw/opencv-python-4.5.4.58/setup.py", line 10, in <module>
    long_description='%s\n\n%s' % (Path('README.rst').read_text(),
ModuleNotFoundError: No module named 'skbuild'

**Comment by Rava77** [comment]
Installation using pip also fails

# pip install pixivdownloader
Traceback (most recent call last):
  File "/usr/bin/pip", line 33, in <module>
    sys.exit(load_entry_point('pip==21.3.1', 'console_scripts', 'pip')())
  File "/usr/bin/pip", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for pip

**Comment by Nachtalb** [comment]
ahh damn, I'll look into it.
